### ISSUE TITLE
How can I write a image file to nodemcu?

### ISSUE THREAD

**Issue by MaticsL** [wangzexi/NodeMCU-HTTP-Server#1]
The `NodeMCU studio` supports only lua files. Thanks for help.

**Comment by wangzexi** [comment]
[ESPlorer](https://esp8266.ru/esplorer/#download)

In the left-bottom of the window, you can see `Upload ...`, and you can upload whatever you want.

![img](https://cloud.githubusercontent.com/assets/13242100/20236018/fdd47114-a8df-11e6-997d-51780eee8196.png)
