### ISSUE TITLE
开启服务后使用http.get 127.0.0.1 返回 超时。请问是什么原因？

### ISSUE THREAD

**Issue by pzh-1991** [wangzexi/NodeMCU-HTTP-Server#11]
开启服务后使用http.get访问 127.0.0.1 返回 超时。请问是什么原因？

**Comment by wangzexi** [comment]
谁访问127.0.0.1超时？

**Comment by pzh-1991** [comment]
esp8266上开httpserver后用http.get自己就超时。html写再小都超时。

**Comment by wangzexi** [comment]
有没有可能因为NodeMCU系统是单线程的，也没有事件循环机制，所以你这边发起请求后处理器就阻塞等待了，那边的响应函数没机会被执行到。

**Comment by pzh-1991** [comment]
那看来是没办法解决了，谢谢啦。

**Comment by wangzexi** [comment]
我认为如果你只需要调用一个本地的函数，是不需要原地绕一圈HTTP协议的。
