### ISSUE TITLE
请求文件时经常内存不足

### ISSUE THREAD

**Issue by LiweiDong** [wangzexi/NodeMCU-HTTP-Server#2]
按照你的博客文章做的wifi配置页面。

* Sending 	index.html
E:M 1584
E:M 1584

**Comment by wangzexi** [comment]
NodeMCU的内存本身就很小，解决方法只能是：少写代码、gzip压缩。

使用这些代码，当时我测试没问题：
https://github.com/wangzexi/NodeMCU-Tutorial/tree/master/4.%E5%AE%9E%E7%8E%B0Web%E9%85%8D%E7%BD%AE%E9%A1%B5%E9%9D%A2/source

**Comment by LiweiDong** [comment]
差不多就是用了这些代码  然后加上了MQTT部分。

仅仅是dofile('httpServer.lua')前后就会增长10K的内存占用

**Comment by LiweiDong** [comment]
```
print("=====MEM:"..collectgarbage("count").."=====")
=====MEM:14.8115234375=====
> dofile("httpServer.lua")
> E:M 1584
print("=====MEM:"..collectgarbage("count").."=====")
=====MEM:25.3701171875=====

```

**Comment by wangzexi** [comment]
我记得好像是，httpServer几乎占满了内存，多加几个middleware程序就崩了。

但我觉得这个httpServer已经不能再精简了。

或许：
你可以把`guessType`删掉，然后每次`Response:sendFile`时手动使用`Response:type`设置。
你还可以把`getStatusText`删掉，将它替换为常量，HTTP协议头中对状态文本要求不严。
你还可以把`Response:send`删掉，这样需要发送变量中的文本时，先写到文件，再用`Response:sendFile`。
你甚至可以把`Response:sendFile`中的发送chunk大小降低，比如从每次读入512byte发送改为每次读入128byte就发送：
```
local buf = file.read(128)
pos = pos + 128
```

**Comment by LiweiDong** [comment]
好的，感谢
